from ..node import Node, Tab
from ..base import wrap
from ..base.colors import Colors
from ..layouts import UiContainerHorizontal, UiContainerVertical
from .interactive import UIButton
from .base_widgets import UIBox
from ..keyinput import Key
from ..event.eventmanager import Event
from ..base.theme import Theme
from ..base.basic import real_len, truncate_ansi, strip_ansi
import re
import time
import subprocess


        
class UILabel(UIBox):
    def __init__(self, weight, text):
        self.text = text
        super().__init__(weight, text)
        self.focusable = False
        
    def display(self, width, height):
        # Apply local color if specified, else apply global theme Secondary color
        if getattr(self, "color", None):
            styled_text = f"{self.color}{self.text}{Colors.RESET}"
        else:
            t_color = Theme.current_color_theme
            styled_text = f"{t_color.SECONDARY}{self.text.replace(chr(10), Colors.RESET + chr(10) + t_color.SECONDARY)}{Colors.RESET}"
            
        lines = wrap(styled_text, width, height, {"tr": "", "tl": "", "br": "", "bl": "", "v": "", "h": ""})
        # Strip trailing empty lines from the wrap output to avoid extra spacing
        while lines and real_len(lines[-1]) == 0:
            lines.pop()
        return lines
    
    
    
try:
    from vibe_load import Loading
    
    class UIBar(UIBox, Loading):
        def __init__(self, weight, finish, label="CHILLING", focusable=False, **kwargs_l):
            # 1. Initialize UIBox for the TUI layout and borders
            # We pass an empty string for text because Loading will generate it later
            self.focusable = focusable
            UIBox.__init__(self, weight=weight, text="", title=label)
            
            # 2. Initialize Loading for the progress engine logic
            # We set print_cli=False so it doesn't mess up your TUI display
            Loading.__init__(self, iterable=None, finish=finish, action=label, print_cli=False, **kwargs_l)
            
            self.width = 80

        def display(self, w, h):
            self.width = w
            chars = Theme.focus_borders if self.selected else Theme.borders
            # Use the UIBox title and the text generated by the Loading engine
            return wrap(self.text, w=w, h=h, title=self.title, title_pos="center", chars=chars)
        
        def update_bar(self, progress):
            # Since we inherited from Loading, we call self.update directly
            # widtha is adjusted to stay inside the UIBox borders
            self.text = self.update(progress, widtha=self.width - 6)

except ImportError:
    pass
    
class ColorPicker(Node):
    def __init__(self, weight=1):
        super().__init__(weight=weight, focusable=True)
        self.colors = Colors.all_fg()
        self.index = 0
    
    def handle_input(self, key):
        event = Event(key)
        modified = False
        if event.is_left:
            self.prev_color()
            modified = True
        elif event.is_right:
            self.next_color()
            modified = True
            
        if modified:
            self.emit("change", self.current_color())

    def next_color(self):
        self.index = (self.index + 1) % len(self.colors)
    
    def prev_color(self):
        self.index = (self.index - 1) % len(self.colors)

    def current_color(self):
        return self.colors[self.index]

    def display(self, width, height):
        chars = Theme.focus_borders if self.selected else Theme.borders
        content = "USE LEFT/RIGHT ARROWS\nTO PICK A COLOUR\n\n"
        for i, color in enumerate(self.colors):
            if i == self.index:
                # Highlight the selected color box
                block = f"{Colors.BG_WHITE}  {Colors.RESET}" 
                label = f" < {Colors.apply('SELECTED', color)} >"
                content += f" {block} {label}\n"
            else:
                block = f"{color}{Colors.BG_BLACK}  {Colors.RESET}"
                content += f" {block}\n"
        
        # ColorPicker content already has ANSI codes, so just wrap it
        return wrap(content, width, height, chars=chars)

                

class UIModal(Node):
    def __init__(self, width_pct=0.5, height_pct=0.5, title="[ Modal ]", text=""):
        super().__init__(weight=1) # Weight doesn't matter much here
        self.width_pct = width_pct
        self.height_pct = height_pct
        self.title = title
        self.text = text
        self.is_active = False

    def display_over(self, screen_buffer, term_width, term_height):
        """
        Takes the fully rendered screen buffer and draws the modal over it.
        Returns the modified screen buffer.
        """
        if not self.is_active:
            return screen_buffer

        # 1. Calculate the modal's absolute dimensions
        modal_w = max(10, int(term_width * self.width_pct))
        modal_h = max(5, int(term_height * self.height_pct))

        # 2. Calculate the top-left starting position to center it
        start_x = (term_width - modal_w) // 2
        start_y = (term_height - modal_h) // 2

        # 3. Generate the modal's content using your existing wrap function
        # We use selected=True styling (thicker borders) to make it pop
        chars = Theme.CURVED
        
        # Apply a background color if your Colors class supports it, 
        # or just standard text to ensure it covers the background
        modal_content = wrap(
            self.text, 
            w=modal_w, 
            h=modal_h, 
            chars=chars, 
            title=self.title, 
            title_pos="center"
        )

        # 4. "Blit" (draw) the modal onto the screen buffer
        new_screen = list(screen_buffer) # Copy the buffer
        
        # We need a helper function to strip ANSI codes from the background line
        # so we can correctly overwrite the characters without breaking color formatting.
        import re
        ansi_regex = re.compile(r'\x1b\[[0-?]*[ -/]*[@-~]')
        
        for i, modal_line in enumerate(modal_content):
            buffer_y = start_y + i
            if 0 <= buffer_y < len(new_screen):
                bg_line = new_screen[buffer_y]
                
                # Preserve background colors by using truncate_ansi for the side parts
                left_part = truncate_ansi(bg_line, start_x)
                # Pad left_part if it's shorter than start_x (visual columns)
                left_part += " " * (start_x - real_len(left_part))
                
                right_part = strip_ansi(bg_line)[start_x + modal_w:]
                
                # Stitch it together: Left BG + Modal Line + Right BG
                new_screen[buffer_y] = f"{left_part}{modal_line}{Colors.RESET}{right_part}"

        return new_screen
    
class UIModalNode(UIModal):
    def __init__(self, node: Node, width_pct=0.5, height_pct=0.5, title="[ Modal ]"):
        super().__init__(width_pct=width_pct, height_pct=height_pct, title=title)
        self.content_node = node
        self.focusable = True

    def handle_input(self, key):
        if self.is_active:
            self.content_node.handle_input(key)

    def display_over(self, screen_buffer, term_width, term_height):
        if not self.is_active:
            return screen_buffer

        # 1. Calculate the modal's absolute dimensions
        modal_w = max(10, int(term_width * self.width_pct))
        modal_h = max(5, int(term_height * self.height_pct))

        # 2. Calculate the top-left starting position to center it
        start_x = (term_width - modal_w) // 2
        start_y = (term_height - modal_h) // 2

        # 3. Render the child node into a local buffer
        # We subtract 2 for the modal's own borders
        inner_w = modal_w - 2
        inner_h = modal_h - 2
        
        # If there's a title, we usually subtract another line for the header bar
        child_h = inner_h
        
        child_output = self.content_node.display(inner_w, child_h)

        # 4. Wrap the child output in the modal's frame
        # We use Theme borders
        chars = Theme.focus_borders if self.selected else Theme.borders
        
        # Manually construct the frame instead of using wrap (which expects raw text)
        res = []
        
        # Top Border with Title
        top_h = chars.get('h', '─')
        if self.title:
            title_str = f" {self.title} "
            left_len = (inner_w - len(title_str)) // 2
            right_len = inner_w - len(title_str) - left_len
            top_line = f"{chars['tl']}{top_h * left_len}{title_str}{top_h * right_len}{chars['tr']}"
        else:
            top_line = f"{chars['tl']}{top_h * inner_w}{chars['tr']}"
        res.append(top_line)

        # Body (Child Output)
        v_char = chars.get('v', '│')
        for i in range(inner_h):
            line = child_output[i] if i < len(child_output) else " " * inner_w
            res.append(f"{v_char}{line}{v_char}")

        # Bottom Border
        res.append(f"{chars['bl']}{top_h * inner_w}{chars['br']}")

        # 5. "Blit" onto the screen buffer
        new_screen = list(screen_buffer)
        ansi_regex = re.compile(r'\x1b\[[0-?]*[ -/]*[@-~]')
        
        for i, modal_line in enumerate(res):
            buffer_y = start_y + i
            if 0 <= buffer_y < len(new_screen):
                bg_line = new_screen[buffer_y]
                
                # Preserve background colors by using truncate_ansi for the side parts
                left_part = truncate_ansi(bg_line, start_x)
                # Pad left_part if it's shorter than start_x (visual columns)
                left_part += " " * (start_x - real_len(left_part))
                
                right_part = strip_ansi(bg_line)[start_x + modal_w:]
                
                # Stitch it together: Left BG + Modal Line + Right BG
                new_screen[buffer_y] = f"{left_part}{modal_line}{Colors.RESET}{right_part}"

        return new_screen
# ignore
class UITree(UIBox):
    def __init__(self, data: dict):
        pass
# end
class UIToast(Node):
    def __init__(self, text="", duration=3, color=Colors.CYAN):
        super().__init__(weight=1, focusable=False)
        self.text = text
        self.duration = duration
        self.start_time = None
        self.is_active = False
        self.color = color

    def show(self, text=None):
        if text: self.text = text
        self.start_time = time.time()
        self.is_active = True

    def display_over(self, screen_buffer, term_width, term_height):
        if not self.is_active:
            return screen_buffer

        if time.time() - self.start_time > self.duration:
            self.is_active = False
            return screen_buffer

        # Calculate dimensions (padding + text)
        toast_w = len(self.text) + 4
        toast_h = 3
        
        # Position: Bottom Right
        start_x = term_width - toast_w - 2
        start_y = term_height - toast_h - 1

        toast_content = wrap(
            f"{self.color}{self.text}{Colors.RESET}", 
            w=toast_w, 
            h=toast_h, 
            chars=Theme.borders
        )

        new_screen = list(screen_buffer)
        ansi_regex = re.compile(r'\x1b\[[0-?]*[ -/]*[@-~]')
        
        for i, toast_line in enumerate(toast_content):
            buffer_y = start_y + i
            if 0 <= buffer_y < len(new_screen):
                bg_line = new_screen[buffer_y]
                clean_bg = ansi_regex.sub('', bg_line)
                
                left_part = clean_bg[:start_x]
                right_part = clean_bg[start_x + toast_w:]
                new_screen[buffer_y] = f"{left_part}{toast_line}{Colors.RESET}{right_part}"

        return new_screen
